{"name": "test_six", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <test_case.TestClass object at 0x000002A44E0F5340>\n\n    def test_six(self):\n        result,data,url = b.customer_save()\n        idresult,u,d = b.get_customer(nowtime)\n>       cus_id = idresult.json()['data']['records'][0]['id']\nE       IndexError: list index out of range\n\ntest_case.py:59: IndexError"}, "start": 1669369869419, "stop": 1669369869593, "uuid": "d076ace2-7ed4-41f0-a078-944c840aecef", "historyId": "9c0a357a43f89da9eea6c1f8c52f4f0c", "testCaseId": "855233f1a88591591b0d29ec2b841726", "fullName": "test_case.TestClass#test_six", "labels": [{"name": "suite", "value": "test_case"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "zjp-wb00211"}, {"name": "thread", "value": "99432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case"}]}